### ISSUE TITLE
GeoIP page difficult to get to

### ISSUE THREAD

**Issue by cr41g1w** [jerriep/airport-explorer-book#1]
For some reason the GeoIP section at https://jerriep.gitbooks.io/airport-explorer-book/content/finishing-touches/geoip/geoip.html never wants to launch in Chrome for me.

**Comment by jerriep** [comment]
Do you mean that the page at that URL does not load in Chrome?

Unfortunately, I do not have much control over that. I host the content for the book on Gitbook, so there may be an issue with their hosting service - which is out of my control.

Is it not perhaps a browser extension which is blocking that page? Try open an Incognito window in Chrome and then try and load that URL in the Incognito window to see if that works.

Otherwise, download the PDF or try another browser

**Comment by cr41g1w** [comment]
Ah yes, it was my ad blocker (uBlock) that was causing the issue, thanks.  It was the only page that I had that problem with though.

**Comment by jerriep** [comment]
Very strange... I use Ghostery and it does not pick up any trackers on that
page.

Well, as long as you can now read it ;)
